spring:
  application:
      name: auth
  redis:
    host: 10.30.0.97
    password: ori18502800930

server:
  port: 3333

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/


security:
  oauth2:
    resource:
      filter-order: 3
    sso:
      filter-order: 3

